name: Lint

on:
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Lint and check formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Lint
        run: npm run lint
      - name: Check formatting
        run: npm run check-prettier
